server:
  port: 8888
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri:
  application:
    name: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
